# Generated by Django 3.1.1 on 2020-10-13 03:48

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ'),
        ),
        migrations.AlterField(
            model_name='card',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='サブタイトル 30文字まで'),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(max_length=15, verbose_name='技術名称 15文字まで'),
        ),
    ]
