# Generated by Django 3.1.1 on 2020-10-16 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20201013_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='book',
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Impression',
        ),
    ]
