# Generated by Django 3.1.1 on 2020-10-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20201016_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='workseat',
            name='Wseatimg',
            field=models.ImageField(default='', upload_to='images/', verbose_name='シートのデータ'),
        ),
        migrations.AddField(
            model_name='workseat',
            name='desc',
            field=models.TextField(default='', verbose_name='ワークシート説明'),
        ),
    ]
