# Generated by Django 3.1.1 on 2020-10-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_workseat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Card',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='tec_img',
            new_name='tecimg',
        ),
    ]
