# Generated by Django 3.1.1 on 2020-10-21 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20201021_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workseat',
            name='Wseatimg',
            field=models.FileField(default='', upload_to='images/', verbose_name='シートのデータ'),
        ),
    ]
