# Generated by Django 3.1.1 on 2020-10-21 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20201021_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workseat',
            name='Wseatimg',
        ),
    ]
