# Generated by Django 3.1.1 on 2020-10-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_workseat_wseatimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='タイトル')),
                ('question1', models.CharField(max_length=50, verbose_name='問1')),
                ('question2', models.CharField(max_length=50, verbose_name='問2')),
                ('question3', models.CharField(max_length=50, verbose_name='問3')),
                ('question4', models.CharField(max_length=50, verbose_name='問4')),
                ('question5', models.CharField(max_length=50, verbose_name='問5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
